version: '3.8'

services:
  europarcel-mcp:
    build: .
    container_name: europarcel-mcp
    environment:
      - EUROPARCEL_API_KEY=${EUROPARCEL_API_KEY}
      - MCP_TRANSPORT=${MCP_TRANSPORT:-stdio}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=production
    stdin_open: true
    tty: true
    restart: unless-stopped
    
  # Optional: HTTP transport service
  europarcel-mcp-http:
    build: .
    container_name: europarcel-mcp-http
    environment:
      - EUROPARCEL_API_KEY=${EUROPARCEL_API_KEY}
      - MCP_TRANSPORT=http
      - MCP_PORT=3000
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    profiles:
      - http 